# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculate.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_calculator(object):
    def setupUi(self, calculator):
        calculator.setObjectName("calculator")
        calculator.resize(870, 545)
        self.result_box = QtWidgets.QLineEdit(calculator)
        self.result_box.setGeometry(QtCore.QRect(650, 230, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(28)
        self.result_box.setFont(font)
        self.result_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.result_box.setAlignment(QtCore.Qt.AlignCenter)
        self.result_box.setObjectName("result_box")
        self.input_box_2 = QtWidgets.QLineEdit(calculator)
        self.input_box_2.setGeometry(QtCore.QRect(380, 230, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.input_box_2.setFont(font)
        self.input_box_2.setAlignment(QtCore.Qt.AlignCenter)
        self.input_box_2.setObjectName("input_box_2")
        self.input_box_1 = QtWidgets.QLineEdit(calculator)
        self.input_box_1.setGeometry(QtCore.QRect(80, 230, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.input_box_1.setFont(font)
        self.input_box_1.setAlignment(QtCore.Qt.AlignCenter)
        self.input_box_1.setObjectName("input_box_1")
        self.set_sign_combo_box = QtWidgets.QComboBox(calculator)
        self.set_sign_combo_box.setGeometry(QtCore.QRect(270, 230, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.set_sign_combo_box.setFont(font)
        self.set_sign_combo_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.set_sign_combo_box.setObjectName("set_sign_combo_box")
        self.set_sign_combo_box.addItem("")
        self.set_sign_combo_box.addItem("")
        self.set_sign_combo_box.addItem("")
        self.set_sign_combo_box.addItem("")
        self.label = QtWidgets.QLabel(calculator)
        self.label.setGeometry(QtCore.QRect(560, 230, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.clear_button = QtWidgets.QPushButton(calculator)
        self.clear_button.setGeometry(QtCore.QRect(150, 410, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(22)
        self.clear_button.setFont(font)
        self.clear_button.setObjectName("clear_button")
        self.calculate_button = QtWidgets.QPushButton(calculator)
        self.calculate_button.setGeometry(QtCore.QRect(490, 410, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(22)
        self.calculate_button.setFont(font)
        self.calculate_button.setObjectName("calculate_button")
        self.frame = QtWidgets.QFrame(calculator)
        self.frame.setGeometry(QtCore.QRect(650, 220, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.retranslateUi(calculator)
        self.clear_button.clicked.connect(self.input_box_1.clear)
        self.clear_button.clicked.connect(self.input_box_2.clear)
        self.clear_button.clicked.connect(self.result_box.clear)
        QtCore.QMetaObject.connectSlotsByName(calculator)

    def retranslateUi(self, calculator):
        _translate = QtCore.QCoreApplication.translate
        calculator.setWindowTitle(_translate("calculator", "Form"))
        self.set_sign_combo_box.setItemText(0, _translate("calculator", "+"))
        self.set_sign_combo_box.setItemText(1, _translate("calculator", "-"))
        self.set_sign_combo_box.setItemText(2, _translate("calculator", "/"))
        self.set_sign_combo_box.setItemText(3, _translate("calculator", "*"))
        self.label.setText(_translate("calculator", "="))
        self.clear_button.setText(_translate("calculator", "clear"))
        self.calculate_button.setText(_translate("calculator", "calculate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    calculator = QtWidgets.QWidget()
    ui = Ui_calculator()
    ui.setupUi(calculator)
    calculator.show()
    sys.exit(app.exec_())
